apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: simple-python
    appstudio.openshift.io/component: devfile-sample-python-basic
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-python-basic
  namespace: dev-release-team-tenant
spec:
  url: https://github.com/scoheb/devfile-sample-python-basic
