apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
  namespace: dev-release-team-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:04035f0366314192d7a8b42b8026c999e8fb746fbad9462eb041ae19e81576f5
        name: my-python
        resources: {}
status: {}
